- name: Download the frp tarball
  get_url:
    url: "https://github.com/fatedier/frp/releases/download/v{{ frpc_version }}/frp_{{ frpc_version }}_linux_arm64.tar.gz"
    dest: /tmp/frp.tar.gz

- name: Ensure frp directory exists
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - /usr/local/frp
    - /etc/frp

- name: Extract the frp tarball
  unarchive:
    src: /tmp/frp.tar.gz
    dest: /usr/local/frp
    remote_src: yes

- name: Create symbolic links
  file:
    src: "/usr/local/frp/frp_{{ frpc_version }}_linux_arm64/frpc"
    dest: /usr/bin/frpc
    state: link

- name: Generate configuration file
  template:
    src: "{{ frpc_config_file }}"
    dest: /etc/frp/frpc.ini
  notify:
    - restart frpc

- name: Generate systemd service file
  template:
    src: frpc.service.j2
    dest: /etc/systemd/system/frpc.service
  notify:
    - restart frpc
